WebProgramming/Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebProgramming.Models
{
    public class News : IEntity
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }

    }
}

WebProgramming/Controllers/NewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProgramming.Extensions;
using WebProgramming.Models;

namespace WebProgramming.Controllers
{
    [Authorize(Roles = "Admin")]
    public class NewsController : Controller
    {
        private readonly NewsDbContext _newsDbContext;

        public NewsController(NewsDbContext newsDbContext)
        {
            _newsDbContext = newsDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddNews()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddNews(NewsModel newsModel)
        {

            News news = new News();
            news.Image = await newsModel.Image.GetBytes();
            news.Title = newsModel.Title;
            news.SubTitle = newsModel.SubTitle;
            news.Description = newsModel.Description;
            await _newsDbContext.News.AddAsync(news);
            await _newsDbContext.SaveChangesAsync();
            return Redirect("/admin/");


        }
        [HttpGet]
        public async Task<IActionResult> UpdateNews(int id)
        {

            var news = await _newsDbContext.News.FindAsync(id);
            NewsModel newsModel = new NewsModel();
            newsModel.Id = news.Id;
            newsModel.Title = news.Title;
            newsModel.SubTitle = news.SubTitle;
            newsModel.Description = news.Description;
            return View(newsModel);

        }
        [HttpPost]
        public async Task<IActionResult> UpdateNews(NewsModel newsModel)
        {

            var news = _newsDbContext.News.Find(newsModel.Id);
            news.Image = await newsModel.Image.GetBytes();
            news.Title = newsModel.Title;
            news.SubTitle = newsModel.SubTitle;
            news.Description = newsModel.Description;
            _newsDbContext.News.Update(news);
            await _newsDbContext.SaveChangesAsync();

            return Redirect("/admin/");
        }
        [HttpGet]
        public async Task<IActionResult> DeleteNews(int id)
        {

            var news = _newsDbContext.News.Find(id);
            _newsDbContext.News.Remove(news);
            await _newsDbContext.SaveChangesAsync();

            return Redirect("/admin/");
        }
    }
}

WebProgramming/Views/News/AddNews.cshtml
@model NewsModel
@{
    Layout = "_AccountLayout";
}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">

            @using (Html.BeginForm("AddNews", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <span class="login100-form-title p-b-32">
                    Add News
                </span>

                <div class="wrap-input100 validate-input m-b-36">
                    @Html.ValidationSummary(false, null, new { @class = "text-danger" })
                </div>

                @Html.LabelFor(x => x.Title, "Title", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
                    @Html.TextBoxFor(x => x.Title, null, new { @class = "input100" })
                    <span class="focus-input100"></span>
                </div>

                @Html.LabelFor(x => x.SubTitle, "SubTitle", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                    <span class="btn-show-pass">
                        <i class="fa fa-eye"></i>
                    </span>
                    @Html.TextBoxFor(x => x.SubTitle, new { @class = "input100" })

                    <span class="focus-input100"></span>
                </div>
                @Html.LabelFor(x => x.Description, "Description", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                    <span class="btn-show-pass">
                        <i class="fa fa-eye"></i>
                    </span>
                    @Html.TextAreaFor(x => x.Description, new { @class = "input100" })

                    <span class="focus-input100"></span>
                </div>
                @Html.LabelFor(x => x.Image, "Image", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                    <span class="btn-show-pass">
                        <i class="fa fa-eye"></i>
                    </span>
                    <input type="file" name="Image" />
                    <span class="focus-input100"></span>
                </div>
                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn" style="margin-right:17%;">
                        Add News
                    </button>
                    <a class="login100-form-btn" href="/admin">Return Admin Panel</a>
                </div>

            }
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

WebProgramming/Views/News/UpdateNews.cshtml
@model NewsModel
@{
    Layout = "_AccountLayout";
}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">

            @using (Html.BeginForm("UpdateNews", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <span class="login100-form-title p-b-32">
                    Update News
                </span>

                <div class="wrap-input100 validate-input m-b-36">
                    @Html.ValidationSummary(false, null, new { @class = "text-danger" })
                </div>
                @Html.LabelFor(x => x.Id, "Id", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
                    @Html.TextBoxFor(x => x.Id, null, new { @class = "input100" ,@readonly="readonly" })
                    <span class="focus-input100"></span>
                </div>
                @Html.LabelFor(x => x.Title, "Title", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
                    @Html.TextBoxFor(x => x.Title, null, new { @class = "input100" })
                    <span class="focus-input100"></span>
                </div>

                @Html.LabelFor(x => x.SubTitle, "SubTitle", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                    <span class="btn-show-pass">
                        <i class="fa fa-eye"></i>
                    </span>
                    @Html.TextBoxFor(x => x.SubTitle, new { @class = "input100" })

                    <span class="focus-input100"></span>
                </div>
                @Html.LabelFor(x => x.Description, "Description", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                    <span class="btn-show-pass">
                        <i class="fa fa-eye"></i>
                    </span>
                    @Html.TextAreaFor(x => x.Description, new { @class = "input100" })

                    <span class="focus-input100"></span>
                </div>
                @Html.LabelFor(x => x.Image, "Image", new { @class = "txt1 p-b-11" })
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                    <span class="btn-show-pass">
                        <i class="fa fa-eye"></i>
                    </span>
                    <input type="file" name="Image" />
                    <span class="focus-input100"></span>
                </div>
                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn" style="margin-right:17%;">
                        Update News
                    </button>
                    <a class="login100-form-btn" href="/admin">Return Admin Panel</a>
                </div>
            }
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>